// Code generated by "stringer -type=PacketType -output=string.go"; DO NOT EDIT.

package servit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hello-0]
	_ = x[GetFile-1]
}

const _PacketType_name = "HelloGetFile"

var _PacketType_index = [...]uint8{0, 5, 12}

func (i PacketType) String() string {
	if i >= PacketType(len(_PacketType_index)-1) {
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketType_name[_PacketType_index[i]:_PacketType_index[i+1]]
}
